export const palette = {
  deepPurple: '#6C5CE7',
  electricBlue: '#0984E3',
  vibrantGreen: '#00B894',
  sunsetOrange: '#FDCB6E',
  coralRed: '#FF7675',
  charcoal: '#2D3436',
  softWhite: '#F5F6FA',
  lavender: '#eae8ff',
  turquoise: '#41ead4',
};

export const lightTheme = {
  mode: 'light',
  background: palette.softWhite,
  text: palette.charcoal,
  card: '#ffffff',
  border: '#E8E9ED',
  primary: palette.deepPurple,
  secondary: palette.electricBlue,
  success: palette.vibrantGreen,
  warning: palette.sunsetOrange,
  error: palette.coralRed,
  accent: palette.electricBlue,
  glow: palette.turquoise,
  muted: '#636E72',
  shadow: 'rgba(45, 52, 54, 0.1)',
};

export const darkTheme = {
  mode: 'dark',
  background: palette.charcoal,
  text: palette.softWhite,
  card: '#1E272E',
  border: '#3C444C',
  primary: palette.deepPurple,
  secondary: palette.electricBlue,
  success: palette.vibrantGreen,
  warning: palette.sunsetOrange,
  error: palette.coralRed,
  accent: palette.electricBlue,
  glow: palette.turquoise,
  muted: '#95A5A6',
  shadow: 'rgba(0, 0, 0, 0.3)',
};

export const themeStyles = (t) => ({
  screen: { flex: 1, backgroundColor: t.background },
  container: { flex: 1, backgroundColor: t.background, padding: 16 },
  scrollContainer: { flexGrow: 1, paddingBottom: 80 },
  title: { fontSize: 28, fontWeight: '700', color: t.text, fontFamily: 'System' },
  subtitle: { fontSize: 16, color: t.muted, marginTop: 4, fontWeight: '500' },
  heading: { fontSize: 20, fontWeight: '600', color: t.text },
  body: { fontSize: 15, color: t.text, lineHeight: 22 },
  caption: { fontSize: 13, color: t.muted },
  card: { backgroundColor: t.card, borderRadius: 16, padding: 16, shadowColor: t.shadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 3 },
  trendCard: { backgroundColor: t.card, borderRadius: 20, overflow: 'hidden', shadowColor: t.shadow, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 5, marginBottom: 16 },
  postCard: { backgroundColor: t.card, borderRadius: 12, padding: 12, marginBottom: 12, shadowColor: t.shadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  buttonPrimary: { backgroundColor: t.primary, paddingVertical: 14, paddingHorizontal: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', shadowColor: t.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  buttonSecondary: { backgroundColor: t.secondary, paddingVertical: 14, paddingHorizontal: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: '#ffffff', fontSize: 16, fontWeight: '600', letterSpacing: 0.5 },
  buttonOutline: { borderColor: t.glow, borderWidth: 2, paddingVertical: 12, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  buttonOutlineText: { color: t.text, fontSize: 15, fontWeight: '600' },
  badge: { backgroundColor: t.accent, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12 },
  badgeText: { color: '#ffffff', fontSize: 12, fontWeight: '600' },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  input: { backgroundColor: t.card, borderColor: t.border, borderWidth: 1, padding: 14, borderRadius: 10, fontSize: 15, color: t.text },
  metricCard: { backgroundColor: t.card, borderRadius: 16, padding: 20, alignItems: 'center', shadowColor: t.shadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 3 },
  fab: { position: 'absolute', right: 20, bottom: 90, width: 60, height: 60, borderRadius: 30, backgroundColor: t.primary, alignItems: 'center', justifyContent: 'center', shadowColor: t.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 12, elevation: 8 },
});