export const palette = {
  charcoal: '#1F2A37',
  graphite: '#2F3E46',
  slate: '#6B778C',
  mint: '#DFF5F1',
  ice: '#ECF8F6',
  sand: '#FAF6F0',
  white: '#FFFFFF',
  jade: '#11B49A',
  teal: '#0F8F9A',
  lime: '#8FD6B5',
  blush: '#FBE8E8',
  coral: '#F37B67',
  amber: '#F7C46C',
  sky: '#9CD8E0',
};

export const lightTheme = {
  mode: 'light',
  background: palette.sand,
  backgroundAlt: palette.ice,
  card: palette.white,
  cardSoft: '#FCFCFB',
  border: '#E3E8EF',
  text: palette.charcoal,
  textMuted: palette.slate,
  primary: palette.jade,
  secondary: palette.sky,
  accent: palette.teal,
  success: '#2AB27B',
  warning: palette.amber,
  error: palette.coral,
  glow: palette.lime,
  shadow: 'rgba(25, 34, 45, 0.12)',
  softShadow: 'rgba(25, 34, 45, 0.06)',
  gradient: ['#FEFEFD', '#ECF8F6'],
  glass: 'rgba(255,255,255,0.7)',
  chip: 'rgba(17, 180, 154, 0.08)',
  dangerSurface: palette.blush,
};

export const darkTheme = {
  mode: 'dark',
  background: '#0F172A',
  backgroundAlt: '#111827',
  card: '#1F2937',
  cardSoft: '#111827',
  border: '#293548',
  text: '#F8FAFC',
  textMuted: '#94A3B8',
  primary: '#34D399',
  secondary: '#22D3EE',
  accent: '#5EEAD4',
  success: '#34D399',
  warning: '#FBBF24',
  error: '#FB7185',
  glow: '#5EEAD4',
  shadow: 'rgba(3, 7, 18, 0.5)',
  softShadow: 'rgba(3, 7, 18, 0.35)',
  gradient: ['#0F172A', '#111827'],
  glass: 'rgba(15,23,42,0.7)',
  chip: 'rgba(94, 234, 212, 0.15)',
  dangerSurface: 'rgba(251, 113, 133, 0.18)',
};

export const themeStyles = (t) => ({
  screen: { flex: 1, backgroundColor: t.background },
  container: { flex: 1, paddingHorizontal: 20 },
  scrollContainer: { flexGrow: 1, paddingBottom: 120 },
  title: { fontSize: 32, fontWeight: '700', color: t.text },
  subtitle: { fontSize: 16, color: t.textMuted, marginTop: 4 },
  heading: { fontSize: 20, fontWeight: '600', color: t.text },
  body: { fontSize: 15, color: t.text, lineHeight: 22 },
  caption: { fontSize: 13, color: t.textMuted },
  sectionHeader: { fontSize: 18, fontWeight: '600', color: t.text, marginBottom: 12 },
  card: {
    backgroundColor: t.card,
    borderRadius: 20,
    padding: 20,
    shadowColor: t.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
    borderWidth: 1,
    borderColor: t.softShadow,
  },
  glassCard: {
    backgroundColor: t.glass,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: t.border,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: t.chip,
    color: t.accent,
    fontWeight: '600',
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: t.border,
    backgroundColor: t.cardSoft,
  },
  chipText: { color: t.text, fontSize: 14, fontWeight: '600' },
  buttonPrimary: {
    backgroundColor: t.primary,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    shadowColor: t.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  buttonSecondary: {
    backgroundColor: t.card,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.border,
  },
  buttonOutline: {
    borderColor: t.border,
    borderWidth: 1,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: t.cardSoft,
  },
  buttonText: { color: '#ffffff', fontSize: 16, fontWeight: '600', letterSpacing: 0.2 },
  buttonOutlineText: { color: t.text, fontSize: 15, fontWeight: '600' },
  badge: { backgroundColor: t.chip, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 14 },
  badgeText: { color: t.accent, fontSize: 12, fontWeight: '700' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  input: {
    backgroundColor: t.card,
    borderColor: t.border,
    borderWidth: 1,
    padding: 16,
    borderRadius: 16,
    fontSize: 16,
    color: t.text,
  },
  metricCard: {
    backgroundColor: t.card,
    borderRadius: 20,
    padding: 20,
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: t.softShadow,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 120,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: t.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: t.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
});